#!/bin/bash
# Takes as input a file containing a list of newline-separated strings
# Outputs a folder, named "cluster_output_" followed by a timestamp, which contains:
#   - the matrix of pairwise distances between strings computed according to each distance metric (CSV files)
#   - the clusters of strings generated by each clustering method (JSON files)

input=$1
timestamp=$(date +%Y%m%d-%H%M%S)
output=./cluster_output_$timestamp/

# distance metrics
distances=('levenshtein' 'damerau' 'jaro' 'winkler' 'jaccard' 'cosine')

# clustering methods
clustering=('ap' 'ms' 'hdbscan')

# n for n-grams based distance metrics
ngrams=4

for cluster in ${clustering[@]}
do
    for dist in ${distances[@]}
    do
        echo "Clustering input using $cluster according to $dist distance between data points"
        python3 stringclusters.py -i $input -o $output -d $dist -c $cluster -n $ngrams
        echo "done\n"
    done
done